### ISSUE TITLE
TypeError: 'Shiboken.ObjectType' object is not iterable

### ISSUE THREAD

**Issue by TheGreatCabbage** [CabbageDevelopment/qasync#1]
System info:
- Python 3.8
- PyQt 5.13.1
- Ubuntu 18.04

This error occurs when importing `qasync`. It is also present in `asyncqt`. It does not appear in Python 3.6. 

Present in `examples/executor_example.py` when debugged with PyCharm.

*It only occurs when debugging*.

```
Traceback (most recent call last):
  File "/home/v/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/192.6817.19/helpers/pydev/pydevd.py", line 2073, in <module>
    main()
  File "/home/v/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/192.6817.19/helpers/pydev/pydevd.py", line 2067, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/v/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/192.6817.19/helpers/pydev/pydevd.py", line 1418, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/v/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/192.6817.19/helpers/pydev/pydevd.py", line 1425, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/v/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/192.6817.19/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/v/pycharm/PyMODA/src/main.py", line 20, in <module>
    from qasync import QEventLoop
  File "/home/v/.local/lib/python3.8/site-packages/qasync/__init__.py", line 54, in <module>
    QtCore = importlib.import_module(QtModuleName + '.QtCore', package=QtModuleName)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
TypeError: 'Shiboken.ObjectType' object is not iterable
```

**Comment by TheGreatCabbage** [comment]
This issue appears to be related to PyCharm's debugger, rather than `qasync`/`asyncqt`. Closed.
