### ISSUE TITLE
Crash during long running proccess in asyncio.create_subprocess_shell on Windows

### ISSUE THREAD

**Issue by esmorun** [CabbageDevelopment/qasync#62]
Hi, I'm executing ffmpeg in an asyncio subprocess to convert a video. Example:

```
command = "ffmpeg  -i \"video.mp4\" -c:v hevc_nvenc -c:a libopus -b:a 96k \"video.mkv\""
proc = await asyncio.create_subprocess_shell(command, stdin=asyncio.subprocess.PIPE, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE)
```
Long running processes will eventually crash the entire PyQt GUI. Sometimes it just crashes to desktop without any output in the Python shell, and sometimes this error message appears:

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\qasync\_windows.py", line 163, in run
    events = self.__proactor.select(0.01)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\qasync\_windows.py", line 69, in select
    self._poll(timeout)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\qasync\_windows.py", line 99, in _poll
    with QtCore.QMutexLocker(self._lock):
RuntimeError: wrapped C/C++ object of type QMutex has been delet
```

The ffmpeg process continues as an orphaned process and finishes the job. Can anybody shed some light on what might be happening? I have tested the same code on Ubuntu and MacOS and have not encountered any issues.

I'm on PyQt 6.2.2 and Python 3.9.9. My main is set up like this:
```
if __name__ == '__main__':
    app = QApplication(sys.argv)
    loop = QEventLoop(app)
    asyncio.set_event_loop(loop)
    
    with loop:
        window = MainWindow()
        window.show()
        loop.run_forever()
```

**Comment by awoimbee** [comment]
I have the same issue with a long running Future. I solved it by using `threading.Lock()` instead of `QMutex`. Not sure if this could have a negative impact.

**Comment by hosaka** [comment]
It is a common problem with Qt bindings for python, where a c++ object underneath gets deleted, and python then tries to use a reference to it. This needs a bit more digging and ideally a reproducible example. Perhaps a long `sleep` call, rather than an ffmpeg encode.

**Comment by dnadlinger** [comment]
I'm also seeing this using (Py)Qt6 and Python 3.11 in https://github.com/dnadlinger/artiq/tree/qt6. No leads as to a reproducible example, unfortunately. The same application works just fine when running against (Py)Qt5. Backtrace is the same as above, though I've also seen nonsensical overload resolution errors in the QMutexLocker constructor (with the same stack trace, presumably due to memory corruption).

I am not very familiar with the internals of Python's GC and how PyQt integrates with it – any ideas what kind of information might be helpful in tracking this down further?

**Comment by dnadlinger** [comment]
@esmorun/@awoimbee You might want to check whether https://github.com/CabbageDevelopment/qasync/pull/87 fixes the issue.

**Comment by hosaka** [comment]
I will address PR later this week, thanks for looking into this.
