### ISSUE TITLE
Application doesn't start in debug mode with Python 3.10 and PyQT6 only

### ISSUE THREAD

**Issue by MateuszKrawczuk** [CabbageDevelopment/qasync#66]
The problem doesn't happen when I use python 3.9.
Error message:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/username/PycharmProjects/myproject/venv/lib/python3.10/site-packages/qasync/__init__.py", line 84, in <module>
    QtCore = importlib.import_module(QtModuleName + ".QtCore", package=QtModuleName)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'PyQt5.QtCore'
```

**Comment by hosaka** [comment]
From the trace you posted, I see nothing pointing the the python version difference. Even though python 3.10 is not currently supported, feel free to create a separate issue with a reproducible example and I can look into it.
